### PR TITLE
Add sphinxjp.themes.solarized to runtime requirements

### PR DESCRIPTION
**Pull request by johannesring**

### CODE REVIEW

**Comment by johannesring** [comment]
@jakirkham - Do you know why CircleCI and conda-forge-linter did not trigger on this?

**Comment by jakirkham** [comment]
CircleCI is going to need to be enabled on each repo manually. 😩 Have done that here and resent the webhook to get CircleCI running here. Please see this [comment]( https://github.com/conda-forge/status/issues/30#issuecomment-270449574 ) for details. Also please let me know if this is something you are able to do on the feedstocks you maintain or not.

As for the linter, sometimes it fails. We tried to improve the service to handle larger numbers of requests more gracefully, but it required some changes like adding parallelism. Of course this is not without a few subtle bugs. :wink: I hope we are able to sort them out. Have resent the webhook to get it running here.

**Comment by johannesring** [comment]
Thanks @jakirkham. In your comment you say that this "likely requires administrative privileges on CircleCI". What is needed for this? Can I just sign up at CircleCI? Sorry, I haven't used CircleCI before.

**Comment by jakirkham** [comment]
Actually this point is irrelevant, we ran a script to "push the button" to enable CircleCI on all PRs from forks on feedstocks again. So nothing actionable for you.

**Comment by johannesring** [comment]
Great, thanks @jakirkham.

**Pull request merged**
