### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.2

### PR DESCRIPTION
**Pull request by johannesring**
This will enable building for Python 3.

### CODE REVIEW

**Comment by johannesring** [comment]
This fails when building for Python 3.6 with the following error message:
``` console
Can't build /Users/travis/build/conda-forge/doconce-feedstock/recipe due to unsatisfiable dependencies:

The following specifications were found to be in conflict:

  - doconce 1.4.0 py36_1

Use "conda info <package>" to see the dependencies for each package.
```
@jakirkham @scopatz - do you know what the problem could be?

**Comment by scopatz** [comment]
There is probably some dependency of docone that doesn't have a python 3.6 package yet.  Try tracing back through the dep tree and rerendering as needed.

**Comment by johannesring** [comment]
Thank you @scopatz - that is likely the problem. It would have been useful with a better error message though. I will try to figure out which dependency doesn't have a Python 3.6 package yet.

**Comment by scopatz** [comment]
No problem, yeah conda build could have a better error message for this, though the one that it there is technically correct.

**Pull request merged**
